# Generated by Django 3.1.6 on 2021-02-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_photo_airtable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychotherapist',
            name='airtable_id',
            field=models.CharField(default='none', max_length=50, unique=True),
        ),
    ]
